# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3aa00759ebb6f1b317b630ce548ca7951fd05a7b22e24ae1123d025b9b1bf6d9676ac48a982cfbc54f0d65f9fe5110245fe8f73cedbabb1d48e93575e58a08e

test:
  secret_key_base: ca38afc6fd4c3e8c08ee7eb686011819b15593054aa8913b916f50c3a4d7f78f50f7bedd455aed93901ee04fd3259224687217480d867324c0f31991066b8547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
